version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/postgresql/data
  
  redis:
    image: redis
    command: /bin/sh -c "redis-server --requirepasss $$REDIS_PASS"
    ports:
      - 6379:6379
    env_file:
      - .env
    volumes:
      - ./redis/data:/data