version: '3.8'
services:
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
    environment:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    command: /bin/sh -c 'redis-server --requirepass ${REDIS_PASS}'
    ports:
      - 6379:6379
    env_file:
      - .env

volumes:
  dbdata: