version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine3.16
    command: /bin/sh -c 'redis-server --requirepass ${REDIS_PASS}'
    ports:
      - 6379:6379
    env_file:
      - .env
    volumes:
      - ./redis/data:/data

volumes:
  dbdata: